---
- name: Setup dan Konfigurasi Server Debian
  hosts: servers
  become: true
  gather_facts: false # Ditunda sampai koneksi SSH siap

  pre_tasks:
    - name: Tunggu hingga service SSH VM siap menerima koneksi
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 180

    - name: Ambil data fakta sistem
      ansible.builtin.setup:

  tasks:
    - name: Install SSH
      ansible.builtin.apt:
        name: openssh-server
        state: present
        
    - name: Pastikan user debian memiliki akses sudo tanpa password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/debian
        line: "debian ALL=(ALL) NOPASSWD:ALL"
        create: yes
        mode: "0440"
        validate: "visudo -cf %s"

    - name: Tampilkan status sukses
      ansible.builtin.debug:
        msg: "Server {{ inventory_hostname }} dengan IP {{ ansible_host }} berhasil dikonfigurasi!"
